spring.application.name=portfolio-backend

server.port= 8081

spring.datasource.url=jdbc:postgresql://localhost:5432/raju_portfolio
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
