# =========================================================
# PRODUCTION PROFILE
# =========================================================

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Never expose internal error details
server.error.include-message=never
server.error.include-stacktrace=never

# Production CORS
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

# Production server
server.forward-headers-strategy=framework