spring.application.name=portfolio-backend

server.port= 8081

spring.datasource.url=jdbc:postgresql://localhost:5432/raju_portfolio
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#changing it to validate from update
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#JWT properties
jwt.secret=${JWT_SECRET}
#jwt.expiration=360000
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}


app.admin.username=${ADMIN_USERNAME}
app.admin.email=${ADMIN_EMAIL}
app.admin.password=${ADMIN_PASSWORD}


#flyway migaration properties
spring.flyway.enabled=true
#Turns Flyway on.

spring.flyway.baseline-on-migrate=true
#If this database already contains tables but does not have Flyway history, establish a baseline instead of assuming the database is empty.

spring.flyway.baseline-version=1
#Current existing database = version 1

spring.flyway.baseline-description=Existing database schema  
#This is simply documentation explaining what version 1 represents.

spring.flyway.locations=classpath:db/migration
